# Generated by Django 6.0.6 on 2026-06-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
