# Generated by Django 6.0.6 on 2026-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_completed_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CompletedTask',
        ),
        migrations.DeleteModel(
            name='ToDoTask',
        ),
    ]
