# Generated by Django 6.0.6 on 2026-06-23 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='tasks.task')),
            ],
        ),
    ]
