# Generated by Django 6.0.6 on 2026-06-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_completed_at_completedtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='tasks',
            new_name='task',
        ),
    ]
